config/routes.rb
Astron::Application.routes.draw do
  resources :units

  resources :rates

  resources :suppliers

  resources :customers

  resources :joborders

  resources :products

  resources :categories

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  

   

end

app/models/joborder.rb
class Joborder < ActiveRecord::Base
  attr_accessible :customer_id, :desc, :joborderid
  validates :customer_id, :desc, :joborderid, presence: true
  
  belongs_to :customer
end

app/controllers/joborders_controller.rb
class JobordersController < ApplicationController
before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  # GET /joborders
  # GET /joborders.json
  def index
    @joborders = Joborder.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @joborders }
    end
  end

  # GET /joborders/1
  # GET /joborders/1.json
  def show
    @joborder = Joborder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @joborder }
    end
  end

  # GET /joborders/new
  # GET /joborders/new.json
  def new
    @joborder = Joborder.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @joborder }
    end
  end

  # GET /joborders/1/edit
  def edit
    @joborder = Joborder.find(params[:id])
  end

  # POST /joborders
  # POST /joborders.json
  def create
    @joborder = Joborder.new(params[:joborder])

    respond_to do |format|
      if @joborder.save
        format.html { redirect_to @joborder, notice: 'Joborder was successfully created.' }
        format.json { render json: @joborder, status: :created, location: @joborder }
      else
        format.html { render action: "new" }
        format.json { render json: @joborder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /joborders/1
  # PUT /joborders/1.json
  def update
    @joborder = Joborder.find(params[:id])

    respond_to do |format|
      if @joborder.update_attributes(params[:joborder])
        format.html { redirect_to @joborder, notice: 'Joborder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @joborder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /joborders/1
  # DELETE /joborders/1.json
  def destroy
    @joborder = Joborder.find(params[:id])
    @joborder.destroy

    respond_to do |format|
      format.html { redirect_to joborders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/joborders_helper.rb
module JobordersHelper
end

app/views/joborders/_form.html.erb
<%= form_for(@joborder) do |f| %>
  <% if @joborder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@joborder.errors.count, "error") %> prohibited this joborder from being saved:</h2>

      <ul>
      <% @joborder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :joborderid %><br />
    <%= f.text_field :joborderid %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br />
	<%= @customers = Customer.find(:all, :order => "name") 
    collection_select(:joborders, :customer_id, @customers, :id, :name, options ={:prompt => "Select a customer"}, :class =>"customer") %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/joborders/edit.html.erb
<h1>Editing joborder</h1>

<%= render 'form' %>

<%= link_to 'Show', @joborder %> |
<%= link_to 'Back', joborders_path %>

app/views/joborders/index.html.erb
<h1>Job Order Maintenance</h1>

<table id="joborders">
  <tr>
    <th>Joborderid</th>
    <th>Desc</th>
    <th>Customer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @joborders.each do |joborder| %>
  <tr>
    <td><%= joborder.joborderid %></td>
    <td><%= joborder.desc %></td>
    <td><%= joborder.customer_id %></td>
    <td><%= link_to 'Show', joborder %></td>
    <td><%= link_to 'Edit', edit_joborder_path(joborder) %></td>
    <td><%= link_to 'Destroy', joborder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Joborder', new_joborder_path %>

app/views/joborders/new.html.erb
<h1>New joborder</h1>

<%= render 'form' %>

<%= link_to 'Back', joborders_path %>

app/views/joborders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Joborderid:</b>
  <%= @joborder.joborderid %>
</p>

<p>
  <b>Desc:</b>
  <%= @joborder.desc %>
</p>

<p>
  <b>Customer:</b>
  <%= @joborder.customer_id %>
</p>


<%= link_to 'Edit', edit_joborder_path(@joborder) %> |
<%= link_to 'Back', joborders_path %>