config/routes.rb
Astron::Application.routes.draw do
  resources :units

  resources :rates

  resources :suppliers

  resources :customers

  resources :joborders

  resources :products

  resources :categories

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  

   

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :desc, :name, :num1, :num2, :user1, :user2
  validates :name, :desc, presence: true
  
  has_many :products, dependent: :destroy
  
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :address, :contactno, :contactperson, :email, :name
  validates :address, :name, presence: true
  
  has_many :joborder
end

app/models/joborder.rb
class Joborder < ActiveRecord::Base
  attr_accessible :customer_id, :desc, :joborderid
  validates :customer_id, :desc, :joborderid, presence: true
  
  belongs_to :customer
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :category_id, :desc, :name
  validates :name, :desc, :category_id, presence: true
  
  belongs_to :category
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  attr_accessible :operatorname, :operatorsymbol, :rateamt, :ratepercent
  validates :operatorname, :operatorsymbol, :rateamt, presence: true
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  attr_accessible :address, :contactno, :contactperson, :email, :name
  validates :name, :address, presence: true
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :unitname, :unitsymbol
  validates :unitname, :unitsymbol, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  # GET /rates
  # GET /rates.json
  def index
    @rates = Rate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rates }
    end
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
    @rate = Rate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rate }
    end
  end

  # GET /rates/new
  # GET /rates/new.json
  def new
    @rate = Rate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rate }
    end
  end

  # GET /rates/1/edit
  def edit
    @rate = Rate.find(params[:id])
  end

  # POST /rates
  # POST /rates.json
  def create
    @rate = Rate.new(params[:rate])

    respond_to do |format|
      if @rate.save
        format.html { redirect_to @rate, notice: 'Rate was successfully created.' }
        format.json { render json: @rate, status: :created, location: @rate }
      else
        format.html { render action: "new" }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rates/1
  # PUT /rates/1.json
  def update
    @rate = Rate.find(params[:id])

    respond_to do |format|
      if @rate.update_attributes(params[:rate])
        format.html { redirect_to @rate, notice: 'Rate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate = Rate.find(params[:id])
    @rate.destroy

    respond_to do |format|
      format.html { redirect_to rates_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  # GET /units
  # GET /units.json
  def index
    @units = Unit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @units }
    end
  end

  # GET /units/1
  # GET /units/1.json
  def show
    @unit = Unit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/new
  # GET /units/new.json
  def new
    @unit = Unit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/1/edit
  def edit
    @unit = Unit.find(params[:id])
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(params[:unit])

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render json: @unit, status: :created, location: @unit }
      else
        format.html { render action: "new" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /units/1
  # PUT /units/1.json
  def update
    @unit = Unit.find(params[:id])

    respond_to do |format|
      if @unit.update_attributes(params[:unit])
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Astron Metal Works Corp"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/joborders_helper.rb
module JobordersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
   def current_user?(user)
    user == current_user
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  
   def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.fullpath
  end
  
  def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in."
      end
    end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
 # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright 2012
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Astron", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
			
			<li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Operation <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Search Product", products_path %></li>
				<li class="divider"></li>
				<li><%= link_to "Purchase Order", categories_path %></li>
				<li class="divider"></li>
                <li><%= link_to "Cost Sheet", products_path %></li>
				<li><%= link_to "Cost Estimate Sheet", products_path %></li>
				<li class="divider"></li>
				<li><%= link_to "Job Order Hours", products_path %></li>
                <li class="divider"></li>
				<li><%= link_to "Inventory", products_path %></li>
				<li><%= link_to "Physical Count", products_path %></li>
              </ul>
            </li>
			
			<li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Maintenance <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
				<li><%= link_to "Customer", customers_path %></li>
				<li><%= link_to "Supplier", suppliers_path %></li>
				<li class="divider"></li>
				<li><%= link_to "Category", categories_path %></li>
                <li><%= link_to "Product", products_path %></li>
				<li><%= link_to "Job Order", joborders_path %></li>
				<li><%= link_to "Units", units_path %></li>
				<li><%= link_to "Rates", rates_path %></li>
              </ul>
            </li>
			
			<li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Finance <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
				<li><%= link_to "Accounts Payable", products_path %></li>
				<li><%= link_to "Accounts Receivable", products_path %></li>
				<li class="divider"></li>
				<li><%= link_to "Product History", categories_path %></li>
              </ul>
            </li>
			
			<li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Reports <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
				<li><%= link_to "Purchase Order", products_path %></li>
				<li class="divider"></li>
				<li><%= link_to "Aging Report", categories_path %></li>
				<li><%= link_to "Comparative Cost Estimate vs Actual Report", categories_path %></li>
              </ul>
            </li>
			
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
				<li><%= link_to "Change Password", products_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
		  <li><%= link_to "Help",    help_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %> 
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
	  <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
	  <%= render 'layouts/footer' %>
	  <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>